---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_install_packages }}"

- name: Run Crawler script
  script:
    cmd: crawler.py "{{ crawl_script_url }}" "{{ crawl_script_depth }}"
  args:
    executable: python3

- name: Ensure nginx is installed and up-to-date
    apt:
      name: nginx
      state: latest

- name: Set nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/

- name: Start nginx
  service:
    name: nginx
    state: started