---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_install_packages }}"

- name: Run Crawler script
  script:
    cmd: crawler.py "{{ crawl_script_url }}" "{{ crawl_script_depth }}"
  args:
    executable: python3

- name: Generate ssl certificate
  shell: >
    openssl req -x509 -nodes -days 1024 -newkey rsa:2048
    -keyout /etc/ssl/private/localhost.key
    -out /etc/ssl/certs/localhost.crt
    -config {{ role_path }}/files/open_ssl.conf -extensions 'v3_req'

- name: Ensure nginx is installed and up-to-date
  apt:
    name: nginx
    state: latest

- name: Set nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Start nginx
  service:
    name: nginx
    state: reloaded
