---
- name: Ensure Pip is installed.
  package:
    name: python3-pip
    state: present

- name: Ensure pip packages are installed
  pip:
    requirements: "{{ role_path }}/files/requirements.txt"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    executable: pip3

- name: Run Crawler script
  script:
    cmd: crawler.py "{{ crawl_script_url }}" "{{ crawl_script_depth }}"
  args:
    executable: python3

- name: Generate ssl certificate
  shell: >
    openssl req -x509 -nodes -days 1024 -newkey rsa:2048
    -keyout /etc/ssl/private/localhost.key
    -out /etc/ssl/certs/localhost.crt
    -config {{ role_path }}/files/open_ssl.conf -extensions 'v3_req'

- name: Ensure nginx is installed and up-to-date
  apt:
    name: nginx
    state: latest

- name: Set nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Start nginx
  service:
    name: nginx
    state: reloaded
